training new model, the num of training epochs is 5000
the shape of batch_data: (14, 384, 512, 10)
the shape of batch_data after transformation (10, 5, 384, 512, 10)
  0%|                                                                                                                                        | 0/5000 [00:00<?, ?it/s]
The shape of u_ml_next: (10, 384, 512, 10)
The shape of self.train_xy: (10, 384, 512, 2)
The shape of u_ml_next: (10, 384, 512, 10)
The shape of self.train_xy: (10, 384, 512, 2)
the shape of batch_data: (14, 384, 512, 10)
the shape of batch_data after transformation (10, 5, 384, 512, 10)
  0%|                                                                                                                                        | 0/5000 [03:21<?, ?it/s]
Traceback (most recent call last):
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 392, in <module>
    trainer.train_model(Test_data, num_epochs=num_epochs)
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 331, in train_model
    err_test = self.eval_model(self.state, test_data)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/api.py", line 620, in cache_miss
    execute = dispatch._xla_call_impl_lazy(fun_, *tracers, **params)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/dispatch.py", line 236, in _xla_call_impl_lazy
    return xla_callable(fun, device, backend, name, donated_invars, keep_unused,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/linear_util.py", line 300, in memoized_fun
    ans = call(fun, *args)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/dispatch.py", line 359, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/dispatch.py", line 445, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2081, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2031, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 271, in eval_model
    u_pred = neural_solver(state, test_data, Nt_test, test_xy)
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 261, in neural_solver
    u, _, _ = lax.fori_loop(1, Nt_test, forward_map, (u, state, test_data, test_xy))
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1691, in fori_loop
    (_, result), _ = scan(_fori_scan_body_fun(body_fun), (lower_, init_val),
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 258, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 244, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 60, in _initial_style_jaxpr
    jaxpr, consts, out_tree = _initial_style_open_jaxpr(
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/lax/control_flow/common.py", line 54, in _initial_style_open_jaxpr
    jaxpr, _, consts = pe.trace_to_jaxpr_dynamic(wrapped_fun, in_avals, debug)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1985, in trace_to_jaxpr_dynamic
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2002, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/lax/control_flow/loops.py", line 1607, in scanned_fun
    return (i + 1, body_fun()(i, x)), None
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/api.py", line 624, in cache_miss
    top_trace.process_call(primitive, fun_, tracers, params))
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 1743, in process_call
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(f, self.main, debug_info=dbg)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2031, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 254, in forward_map
    u = test_data[i].at[:,1:-1,1:-1,:].set(u_ml_out[:,1:-1,1:-1,:])
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 5222, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 71, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 104, in _scatter_impl
    y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1158, in broadcast_to
    return _broadcast_to(array, shape)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 411, in _broadcast_to
    raise ValueError(msg.format(arr_shape, shape))
jax._src.traceback_util.UnfilteredStackTrace: ValueError: Incompatible shapes for broadcasting: (10, 382, 510, 10) and requested shape (6, 382, 510, 10)
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 392, in <module>
    trainer.train_model(Test_data, num_epochs=num_epochs)
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 331, in train_model
    err_test = self.eval_model(self.state, test_data)
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 271, in eval_model
    u_pred = neural_solver(state, test_data, Nt_test, test_xy)
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 261, in neural_solver
    u, _, _ = lax.fori_loop(1, Nt_test, forward_map, (u, state, test_data, test_xy))
  File "/work/09012/haoli1/ls6/hurricane/code/hurr_u_net_2d0.0.py", line 254, in forward_map
    u = test_data[i].at[:,1:-1,1:-1,:].set(u_ml_out[:,1:-1,1:-1,:])
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 5222, in set
    return scatter._scatter_update(self.array, self.index, values, lax.scatter,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 71, in _scatter_update
    return _scatter_impl(x, y, scatter_op, treedef, static_idx, dynamic_idx,
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/ops/scatter.py", line 104, in _scatter_impl
    y = jnp.broadcast_to(y, tuple(indexer.slice_shape))
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 1158, in broadcast_to
    return _broadcast_to(array, shape)
  File "/work/09012/haoli1/ls6/JAX/lib/python3.9/site-packages/jax/_src/numpy/util.py", line 411, in _broadcast_to
    raise ValueError(msg.format(arr_shape, shape))
ValueError: Incompatible shapes for broadcasting: (10, 382, 510, 10) and requested shape (6, 382, 510, 10)